In [1]:
import matplotlib.pyplot as plt

In [2]:
%matplotlib notebook

In [3]:
import  numpy as np

In [4]:
data = np.arange(10)

In [5]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
plt.plot(data)

<IPython.core.display.Javascript object>

In [7]:
fig = plt.figure()

<IPython.core.display.Javascript object>

In [8]:
ax1 = fig.add_subplot(2,2,1)

In [9]:
ax2 = fig.add_subplot(2,2,2)

In [10]:
ax3 = fig.add_subplot(2,2,3)

In [11]:
ax4 = fig.add_subplot(2,2,4)

In [12]:
plt.plot(np.random.randn(50).cumsum(), 'k--')

In [13]:
plt.plot(np.random.randn(50).cumsum(), 'k--')

In [14]:
ax1.hist(np.random.randn(100), bins=20, color='k', alpha=0.3)

(array([ 2.,  4.,  2.,  3.,  9., 11., 14.,  7.,  7.,  5.,  4.,  9.,  6.,
         6.,  3.,  2.,  3.,  1.,  0.,  2.]),
 array([-2.11696494, -1.88819111, -1.65941728, -1.43064345, -1.20186962,
        -0.97309579, -0.74432196, -0.51554813, -0.2867743 , -0.05800047,
         0.17077336,  0.39954719,  0.62832102,  0.85709485,  1.08586868,
         1.31464251,  1.54341634,  1.77219017,  2.000964  ,  2.22973783,
         2.45851166]),
 <BarContainer object of 20 artists>)

In [15]:
ax2.scatter(np.arange(30), np.arange(30) + 3 * np.random.randn(30))

In [17]:
ax3.hist(np.random.randn(50).cumsum())

(array([ 4.,  4.,  2.,  0.,  8.,  7.,  4.,  4.,  5., 12.]),
 array([-1.75955155, -0.46756567,  0.82442021,  2.11640608,  3.40839196,
         4.70037783,  5.99236371,  7.28434959,  8.57633546,  9.86832134,
        11.16030722]),
 <BarContainer object of 10 artists>)

In [19]:
fig,axes = plt.subplots(2,3)

<IPython.core.display.Javascript object>

In [20]:
fig,axes = plt.subplots(2,2,sharex=True,sharey=True)

<IPython.core.display.Javascript object>

In [21]:
for i in range(2):
    for j in range(2):
        axes[i,j].hist(np.random.randn(500),bins=50,color='k',alpha=0.5)

In [22]:
plt.subplots_adjust(wspace=0,hspace=0)

In [23]:
data = np.random.randn(300).cumsum()

In [24]:
data

array([ 2.93991711e-01,  2.09623032e-01, -6.71514041e-01, -9.53115833e-01,
       -1.75295378e+00, -1.05758688e+00, -6.25867868e-01,  1.71933794e+00,
        2.47472182e+00,  2.11509039e+00,  1.99406742e+00,  1.33962671e+00,
        2.18803857e+00,  2.35419811e+00,  2.37339940e+00,  1.67946971e+00,
        1.47403139e+00,  2.14409394e+00,  2.60677019e+00,  1.70138105e+00,
        1.81738789e+00, -2.66191447e-02,  5.00979738e-01,  7.47680689e-01,
        1.02521655e+00, -7.60122023e-01,  1.85646481e-02,  4.77999808e-01,
        1.55879459e+00,  1.62087517e+00,  2.41630693e-01,  2.27301430e+00,
        1.51215579e+00,  1.24865482e-01, -1.15312919e+00, -2.07140468e+00,
       -1.04126684e+00, -1.05046127e+00, -1.57031669e+00, -8.15157718e-01,
        5.63397619e-01,  1.60334072e+00,  6.85819901e-01,  8.91431001e-01,
        4.36815495e-01, -1.18188819e+00, -7.24043260e-01, -5.79203335e-01,
       -1.42454763e+00, -5.46784165e-01,  6.33528579e-02, -1.05344634e+00,
       -1.87399658e+00, -

In [25]:
data = np.random.randn(300)

In [26]:
data

array([-0.97074519, -1.47716125, -1.09736917,  1.07498804, -0.07045513,
       -0.44790338,  1.04431996,  1.19605985, -1.27305774, -0.77277519,
        0.52380423,  0.99172927,  0.7677854 ,  0.74850693,  0.45050053,
       -0.05954176,  0.4475942 ,  1.34256265,  0.08898154,  1.41583751,
        1.74000814,  1.79133467, -0.83301225, -1.18551159,  0.42944447,
        0.93683278, -1.69685136, -0.64431088, -0.33374526, -0.17987683,
       -0.23869205, -0.17498673,  0.2534097 , -0.89951394, -0.06531624,
        1.32949068,  0.93911604, -0.86254552,  0.23796901, -1.29950221,
       -0.29024981, -0.25831681,  0.11335128,  0.20760186, -0.1227802 ,
       -1.61933934,  1.07698047, -0.64613279,  1.1174653 ,  0.01945485,
        0.19427761, -0.50033213,  0.06531267, -0.64495457,  0.89744064,
       -0.93951378, -0.86995644,  1.91571624, -2.11617301,  0.2170939 ,
       -1.23487016, -0.43131742, -0.07523769, -0.06748772,  0.07300237,
       -0.6702205 ,  0.86658715, -0.65447697, -0.35285699, -0.36

In [27]:
data = np.random.randn(30).cumsum()

In [28]:
plt.plot(data,'k--',label='Default')

In [29]:
plt.plot(data,'k-',drawstyle='steps-post',label='steps-post')

In [30]:
plt.legend(loc='best')

In [31]:
%matplotlib notebook

In [32]:
fig = plt.figure()

<IPython.core.display.Javascript object>

In [34]:
ax = fig.add_subplot(1,1,1)

In [35]:
ax.plot(np.random.randn(1000).cumsum())

In [39]:
plt.show()

In [40]:
fig.show()