In [2]:
# 处理丢失数据
import pandas as pd
import numpy as np

string_data = pd.Series(['aardvardk', 'aaaaaaa', np.nan, 'avacoao'])

In [3]:
string_data

0    aardvardk
1      aaaaaaa
2          NaN
3      avacoao
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 8])

In [8]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    8.0
dtype: float64

In [9]:
data.dropna()

0    1.0
2    3.5
4    8.0
dtype: float64

In [12]:
data = pd.DataFrame([[1, 6.5, 3], [1, NA, NA], [NA, NA, NA], [NA, 6.5, 1]])

In [13]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  1.0

In [14]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  1.0

In [16]:
data.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  1.0

In [18]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  1.0

In [19]:
df = pd.DataFrame(np.random.randn(7, 3))

In [20]:
df

0         1         2
0  0.706658 -0.095881  0.718754
1  0.884763  0.309745 -0.058123
2  0.647373  1.326629 -1.189512
3 -0.752230 -0.594687  0.069692
4  0.023801 -0.719244 -0.882473
5 -0.749476  0.117948  0.558784
6  0.742058  0.064887 -1.352671

In [21]:
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [22]:
df

0         1         2
0  0.706658       NaN       NaN
1  0.884763       NaN       NaN
2  0.647373       NaN -1.189512
3 -0.752230       NaN  0.069692
4  0.023801 -0.719244 -0.882473
5 -0.749476  0.117948  0.558784
6  0.742058  0.064887 -1.352671

In [23]:
df.dropna()

0         1         2
4  0.023801 -0.719244 -0.882473
5 -0.749476  0.117948  0.558784
6  0.742058  0.064887 -1.352671

In [24]:
df.dropna(thresh=2)

0         1         2
2  0.647373       NaN -1.189512
3 -0.752230       NaN  0.069692
4  0.023801 -0.719244 -0.882473
5 -0.749476  0.117948  0.558784
6  0.742058  0.064887 -1.352671

In [26]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.706658  0.500000  0.000000
1  0.884763  0.500000  0.000000
2  0.647373  0.500000 -1.189512
3 -0.752230  0.500000  0.069692
4  0.023801 -0.719244 -0.882473
5 -0.749476  0.117948  0.558784
6  0.742058  0.064887 -1.352671

In [27]:
_ = df.fillna(0, inplace=True)

In [28]:
df

0         1         2
0  0.706658  0.000000  0.000000
1  0.884763  0.000000  0.000000
2  0.647373  0.000000 -1.189512
3 -0.752230  0.000000  0.069692
4  0.023801 -0.719244 -0.882473
5 -0.749476  0.117948  0.558784
6  0.742058  0.064887 -1.352671

In [29]:
df = pd.DataFrame(np.random.randn(6, 3))

In [30]:
df

0         1         2
0  0.396658  0.523204 -0.003273
1  0.639943  0.247952 -2.909680
2 -1.923978 -0.210197  1.322247
3 -0.442195 -0.553813  0.742686
4 -1.208262 -1.064146 -1.933621
5 -0.389214 -0.411751 -0.141272

In [32]:
df.iloc[2:, 1] = NA

In [33]:
df.iloc[4:, 2] = NA

In [34]:
df

0         1         2
0  0.396658  0.523204 -0.003273
1  0.639943  0.247952 -2.909680
2 -1.923978       NaN  1.322247
3 -0.442195       NaN  0.742686
4 -1.208262       NaN       NaN
5 -0.389214       NaN       NaN

In [35]:
df.fillna(method='ffill')

0         1         2
0  0.396658  0.523204 -0.003273
1  0.639943  0.247952 -2.909680
2 -1.923978  0.247952  1.322247
3 -0.442195  0.247952  0.742686
4 -1.208262  0.247952  0.742686
5 -0.389214  0.247952  0.742686

In [36]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.396658  0.523204 -0.003273
1  0.639943  0.247952 -2.909680
2 -1.923978  0.247952  1.322247
3 -0.442195  0.247952  0.742686
4 -1.208262       NaN  0.742686
5 -0.389214       NaN  0.742686

In [37]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [38]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [39]:
# 7.2 数据转换
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})

In [40]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [41]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [43]:
data['v1'] = range(7)

In [44]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [45]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [46]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [48]:
# 利用函数或映射进行数据转换
data = pd.DataFrame(
    {'food': ['bacon', 'pulled pord', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'],
     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pord     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [56]:
# 添加一列，说明食物的来源
meat_to_animal = {'bacon':'pig','pulled pord':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}

In [57]:
meat_to_animal

{'bacon': 'pig',
 'pulled pord': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [58]:
lowercased = data['food'].str.lower()

In [59]:
lowercased

0          bacon
1    pulled pord
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [60]:
data['animal'] = lowercased.map(meat_to_animal)

In [61]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pord     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [62]:
# map函数是实现元素转换以及其他清理工作的便捷方式
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [63]:
# replace
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [64]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [66]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [68]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [69]:
# 重命名轴索引

In [70]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])

In [71]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [72]:
transform = lambda  x:x[:4].upper()

In [73]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [74]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [75]:
data.index = data.index.map(transform)

In [76]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [77]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [78]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [79]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [80]:
data.rename(index={'OHIO':'ddooda'},columns={'one':'mmp','two':'mmp2'})

mmp  mmp2  three  four
ddooda    0     1      2     3
COLO      4     5      6     7
NEW       8     9     10    11

In [81]:
# 离散化和面元划分
# 为了便于分析,连续数据离散化和面元
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [82]:
bins = [18,25,35,60,100]

In [83]:
cats = pd.cut(ages,bins)

In [84]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [85]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [86]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [87]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [88]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [90]:
pd.cut(ages,[18,26,36,61,100],right=False).codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [91]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [92]:
pd.cut(ages,bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [93]:
pd.cut(ages,bins,labels=group_names).codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [94]:
data = np.random.rand(20)

In [95]:
data

array([0.61670014, 0.37377696, 0.45882936, 0.30105643, 0.32901091,
       0.21304028, 0.23255681, 0.1952055 , 0.09570313, 0.69323403,
       0.51907632, 0.18368103, 0.45522917, 0.42775475, 0.79207072,
       0.81190332, 0.58131688, 0.15711157, 0.52858599, 0.5575711 ])

In [96]:
pd.cut(data,4,precision=2)

[(0.45, 0.63], (0.27, 0.45], (0.45, 0.63], (0.27, 0.45], (0.27, 0.45], ..., (0.63, 0.81], (0.45, 0.63], (0.095, 0.27], (0.45, 0.63], (0.45, 0.63]]
Length: 20
Categories (4, interval[float64, right]): [(0.095, 0.27] < (0.27, 0.45] < (0.45, 0.63] < (0.63, 0.81]]

In [97]:
# 等分切分qcut
data = np.random.randn(1000)

In [98]:
data

array([ 3.59020969e-01, -1.26610253e+00,  7.72085928e-01,  3.29110061e-01,
        1.88836438e+00, -2.01194539e-01, -1.18543441e+00, -6.82275101e-01,
       -2.11389420e+00, -5.12932408e-01,  3.25575282e-01,  2.02324502e-01,
       -1.30573783e-01, -5.40140317e-02,  4.55565211e-01, -7.12837883e-01,
        1.53731676e+00, -7.58769623e-01, -5.11108133e-01, -1.51562208e+00,
        1.31184343e+00, -3.48235226e-01, -3.53637555e-01,  3.65024388e-01,
       -2.54444432e-01,  8.68324898e-01,  2.76902014e-01, -4.49888905e-01,
       -6.65305715e-01, -1.24250922e+00,  1.03100199e+00, -4.20314500e-01,
       -1.20722974e-02, -1.15420227e+00,  2.96613793e-01, -3.65980483e-01,
        2.18348128e+00, -4.75790274e-01, -1.28177438e-01,  1.49303683e+00,
       -7.77407039e-01,  1.22795319e+00, -8.81239697e-02,  4.52972758e-01,
       -4.93727609e-01, -7.13132382e-01, -6.65447561e-01, -1.41464621e+00,
       -3.07871548e-01,  4.15670105e-01, -7.33988888e-01,  1.20817125e+00,
       -7.33460602e-01,  

In [99]:
cats = pd.qcut(data,4)

In [100]:
cats

[(-0.0715, 0.645], (-3.078, -0.709], (0.645, 3.388], (-0.0715, 0.645], (0.645, 3.388], ..., (-0.709, -0.0715], (-0.709, -0.0715], (-0.709, -0.0715], (0.645, 3.388], (-3.078, -0.709]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.078, -0.709] < (-0.709, -0.0715] < (-0.0715, 0.645] < (0.645, 3.388]]

In [101]:
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(-0.0715, 1.228], (-1.348, -0.0715], (-0.0715, 1.228], (-0.0715, 1.228], (1.228, 3.388], ..., (-1.348, -0.0715], (-1.348, -0.0715], (-1.348, -0.0715], (1.228, 3.388], (-1.348, -0.0715]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.078, -1.348] < (-1.348, -0.0715] < (-0.0715, 1.228] < (1.228, 3.388]]

In [ ]:
# 这个对切分可以出现一种切分很有用